from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, Spacer
from reportlab.lib import colors
import io
import datetime


def build_evidence_pdf(
    incident_id: str,
    severity: str,
    timeline: list,
    citations: list,
    incidents: list,
) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()
    story = []

    # Header
    story.append(
        Paragraph(
            "<b>GradientGuard — DORA Incident Evidence Package</b>",
            styles["Heading1"],
        )
    )
    story.append(
        Paragraph(
            f"Incident ID: {incident_id} | Severity: {severity} | "
            f"Generated: {datetime.datetime.utcnow().isoformat()}Z",
            styles["Normal"],
        )
    )
    story.append(Spacer(1, 12))

    # Executive Summary
    story.append(
        Paragraph("<b>1. Executive Summary</b>", styles["Heading2"])
    )
    story.append(
        Paragraph(
            f"This package documents DORA compliance evidence for incident {incident_id}. "
            f"{len(incidents)} threshold breach(es) detected. Severity: {severity}.",
            styles["Normal"],
        )
    )
    story.append(Spacer(1, 10))

    # Incident Timeline
    story.append(
        Paragraph("<b>2. Incident Timeline</b>", styles["Heading2"])
    )
    if timeline:
        tdata = [["Timestamp", "Event", "System", "Impact"]]
        for t in timeline:
            tdata.append(
                [
                    t.get("timestamp", "")[:19],
                    t.get("event", ""),
                    t.get("system", ""),
                    t.get("impact", ""),
                ]
            )
        table = Table(tdata, colWidths=[120, 200, 80, 80])
        table.setStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#0c0c30"),
                ),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                (
                    "ROWBACKGROUNDS",
                    (0, 1),
                    (-1, -1),
                    [colors.white, colors.HexColor("#f0f0ff")],
                ),
            ]
        )
        story.append(table)
    story.append(Spacer(1, 10))

    # DORA Citations
    story.append(
        Paragraph(
            "<b>3. Applicable DORA Regulation Citations</b>", styles["Heading2"]
        )
    )
    for c in citations[:5]:
        story.append(
            Paragraph(f"<b>{c['article']}</b>", styles["Heading3"])
        )
        story.append(Paragraph(c["text"][:500], styles["Normal"]))
        story.append(Spacer(1, 6))

    # Attestation
    story.append(Spacer(1, 20))
    story.append(Paragraph("<b>4. Attestation</b>", styles["Heading2"]))
    story.append(
        Paragraph(
            "This evidence package was auto-generated by GradientGuard running on "
            "DigitalOcean Gradient™ AI Platform. It is provided for audit purposes "
            "under DORA Article 17 (ICT-related incident management).",
            styles["Normal"],
        )
    )

    doc.build(story)
    return buf.getvalue()
