import { Router, Request, Response } from "express";
import { streamCounselResponse } from "../services/gradient";
import { db } from "../services/db";
import { incidents } from "../db/schema";
import { desc, eq } from "drizzle-orm";
import { broadcast } from "../services/sse";
import { z } from "zod";
import { env } from "../lib/env";
import {
  createFallbackIncident,
  listFallbackIncidents,
  updateFallbackIncidentEvidence,
} from "../services/fallback-store";

export const agentsRouter = Router();

/** Builds a real PDF in Node when the EvidenceForge agent is unavailable. */
async function generateFallbackEvidence(payload: {
  incident_id: string;
  severity: string;
  dora_articles: string[];
  incidents: unknown[];
}): Promise<void> {
  try {
    const now = new Date().toISOString();
    const articleList = payload.dora_articles.map((a) => `• ${a}`).join("\n");
    const incidentList = (payload.incidents as Array<Record<string, unknown>>)
      .map((i) => `• ${String(i.type ?? "incident")}: ${String(i.details ?? "")}`)
      .join("\n");

    // Build a complete PDF using raw PDF syntax (no external deps)
    const lines = [
      "GradientGuard - DORA Incident Evidence Package",
      `Incident ID: ${payload.incident_id}`,
      `Severity: ${payload.severity}`,
      `Generated: ${now}`,
      "",
      "1. EXECUTIVE SUMMARY",
      `This package documents DORA compliance evidence for incident ${payload.incident_id}.`,
      `Severity: ${payload.severity} | ${payload.dora_articles.length} DORA article(s) triggered.`,
      "",
      "2. TRIGGERED DORA ARTICLES",
      articleList,
      "",
      "3. INCIDENT DETAILS",
      incidentList,
      "",
      "4. ATTESTATION",
      "Auto-generated by GradientGuard on DigitalOcean Gradient AI Platform.",
      "Provided for audit purposes under DORA Article 17 (Incident Management).",
    ];

    // Encode as a simple but valid PDF
    const textContent = lines
      .map((l, i) => `BT /F1 ${l.startsWith("1.") || l.startsWith("2.") || l.startsWith("3.") || l.startsWith("4.") ? "12" : "10"} Tf 50 ${720 - i * 18} Td (${l.replace(/[()\\]/g, "")}) Tj ET`)
      .join("\n");

    const streamLen = Buffer.byteLength(textContent, "utf8");
    const pdf = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj
4 0 obj<</Length ${streamLen}>>
stream
${textContent}
endstream
endobj
5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj
xref
0 6
0000000000 65535 f
trailer<</Root 1 0 R/Size 6>>
startxref
9
%%EOF`;

    const b64 = Buffer.from(pdf, "utf8").toString("base64");
    const dataUrl = `data:application/pdf;base64,${b64}`;

    await db
      .update(incidents)
      .set({ evidenceUrl: dataUrl, evidenceGeneratedAt: new Date(), updatedAt: new Date() })
      .where(eq(incidents.id, payload.incident_id));

    console.log(`Fallback evidence PDF stored for incident ${payload.incident_id}`);
  } catch (err) {
    console.error("Fallback evidence generation failed:", err);
  }
}

async function dispatchDownstreamAgents(payload: {
  incident_id: string;
  severity: "P1" | "P2" | "P3";
  dora_articles: string[];
  incidents: unknown[];
}): Promise<void> {
  const hasEvidence =
    Boolean(env.GRADIENT_AGENT_URL_EVIDENCE) &&
    Boolean(env.GRADIENT_AGENT_KEY_EVIDENCE);
  const hasRemediation =
    Boolean(env.GRADIENT_AGENT_URL_REMEDIATION) &&
    Boolean(env.GRADIENT_AGENT_KEY_REMEDIATION);

  if (!hasEvidence && !hasRemediation) {
    return;
  }

  const body = { messages: [{ role: "user", content: JSON.stringify(payload) }] };
  const tasks: Array<Promise<void>> = [];

  if (hasEvidence) {
    tasks.push(
      fetch(env.GRADIENT_AGENT_URL_EVIDENCE, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${env.GRADIENT_AGENT_KEY_EVIDENCE}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(120_000), // 2 min max
      })
        .then(async (res) => {
          if (!res.ok) {
            console.error(`Evidence agent returned ${res.status} — using server-side fallback`);
            await generateFallbackEvidence(payload);
            return;
          }
          const json = (await res.json()) as { evidence_url?: string };
          if (json.evidence_url) {
            try {
              await db
                .update(incidents)
                .set({
                  evidenceUrl: json.evidence_url,
                  evidenceGeneratedAt: new Date(),
                  updatedAt: new Date(),
                })
                .where(eq(incidents.id, payload.incident_id));
              console.log(`Evidence stored for incident ${payload.incident_id}`);
            } catch {
              updateFallbackIncidentEvidence(payload.incident_id, json.evidence_url);
            }
          } else {
            await generateFallbackEvidence(payload);
          }
        })
        .catch(async (err: unknown) => {
          console.error("Evidence agent dispatch failed:", err);
          await generateFallbackEvidence(payload);
        })
    );
  }

  if (hasRemediation) {
    tasks.push(
      fetch(env.GRADIENT_AGENT_URL_REMEDIATION, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${env.GRADIENT_AGENT_KEY_REMEDIATION}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(body),
      })
        .then(() => undefined)
        .catch(() => undefined)
    );
  }

  await Promise.all(tasks);
}

// POST /api/counsel — stream compliance Q&A from A4
agentsRouter.post("/counsel", async (req: Request, res: Response) => {
  const { question } = req.body as { question?: string };
  if (!question || typeof question !== "string") {
    res.status(400).json({ error: "question is required" });
    return;
  }
  await streamCounselResponse(question, res);
});

// POST /api/simulate — trigger a demo P1 incident
agentsRouter.post("/simulate", async (req: Request, res: Response) => {
  const demoIncidents = [
    {
      type: "droplet_down",
      resource_id: "demo-001",
      resource_name: "prod-api-01",
      dora_article: "Article 11(3) - ICT continuity",
      rto_breach: true,
      details: "Demo: Droplet prod-api-01 is off",
    },
    {
      type: "database_unavailable",
      resource_id: "demo-db-001",
      resource_name: "prod-postgres",
      dora_article: "Article 11(2) - Data backup and recovery",
      rpo_breach: true,
      details: "Demo: Database prod-postgres is unavailable",
    },
  ];

  try {
    const [created] = await db
      .insert(incidents)
      .values({
        severity: "P1",
        doraArticles: [
          "Article 11(3) - ICT continuity",
          "Article 11(2) - Data backup and recovery",
        ],
        details: demoIncidents,
        status: "open",
      })
      .returning();

    broadcast("incident", created);

    // Dispatch evidence + remediation agents in the background
    void dispatchDownstreamAgents({
      incident_id: created.id,
      severity: "P1",
      dora_articles: created.doraArticles as string[],
      incidents: demoIncidents,
    });

    res.status(201).json({
      message: "Demo P1 incident created",
      incident_id: created.id,
    });
  } catch (error) {
    console.error("POST /api/simulate failed", error);
    const fallback = createFallbackIncident({
      severity: "P1",
      doraArticles: [
        "Article 11(3) - ICT continuity",
        "Article 11(2) - Data backup and recovery",
      ],
      details: demoIncidents,
      status: "open",
    });

    broadcast("incident", fallback);

    res.status(201).json({
      message: "Demo P1 incident created",
      incident_id: fallback.id,
      storage: "memory",
    });

    const downstreamPayload = {
      incident_id: fallback.id,
      severity: "P1" as const,
      dora_articles: fallback.doraArticles,
      incidents: demoIncidents,
    };
    void dispatchDownstreamAgents(downstreamPayload);
  }
});

// GET /api/compliance/score — compute live DORA score
agentsRouter.get("/compliance/score", async (_req: Request, res: Response) => {
  try {
    const openIncidents = await db.query.incidents.findMany({
      where: (t, { eq }) => eq(t.status, "open"),
      orderBy: [desc(incidents.detectedAt)],
      limit: 50,
    });

    let score = 100;
    const breakdown: Record<string, number> = {
      "Article 11": 100,
      "Article 17": 100,
      "Article 19": 100,
      "Article 25": 100,
      "Article 28": 100,
    };

    for (const inc of openIncidents) {
      const deduction =
        inc.severity === "P1" ? 20 : inc.severity === "P2" ? 10 : 5;
      score = Math.max(0, score - deduction);

      const articles = (inc.doraArticles as string[]) ?? [];
      for (const article of articles) {
        for (const key of Object.keys(breakdown)) {
          if (article.includes(key)) {
            breakdown[key] = Math.max(0, (breakdown[key] ?? 100) - deduction);
          }
        }
      }
    }

    res.json({ score, breakdown, open_incidents: openIncidents.length });
  } catch (error) {
    console.error("GET /api/compliance/score failed", error);
    const openIncidents = listFallbackIncidents({ status: "open" });
    let score = 100;
    const breakdown: Record<string, number> = {
      "Article 11": 100,
      "Article 17": 100,
      "Article 19": 100,
      "Article 25": 100,
      "Article 28": 100,
    };

    for (const inc of openIncidents) {
      const deduction =
        inc.severity === "P1" ? 20 : inc.severity === "P2" ? 10 : 5;
      score = Math.max(0, score - deduction);

      for (const article of inc.doraArticles ?? []) {
        for (const key of Object.keys(breakdown)) {
          if (article.includes(key)) {
            breakdown[key] = Math.max(0, (breakdown[key] ?? 100) - deduction);
          }
        }
      }
    }

    res.json({
      score,
      breakdown,
      open_incidents: openIncidents.length,
      storage: "memory",
    });
  }
});
